### PR TITLE
Changes path for Drosophila and Yeast organisms. Add wildcard contrai…

### PR DESCRIPTION
**Pull request by SebastienNin**
…ns for those organisms in gtftk_retrieve. But need to find a better way to do it.

### CODE REVIEW

**Comment by SebastienNin** [comment]
@guillaumecharbonnier I finished my tests, all work fine on my side. Cand you review this commit?

**Comment by guillaumecharbonnier** [comment]
Could you send me a featureCounts table produced by the routine workflow for human RNA-Seq ?
I would like to check first how it handle in biojupies. Especially since I think the merge-attribute gtf will result in duplicates gene_symbol for biojupies.

**Comment by SebastienNin** [comment]
I'm making one now, I removed my subread output folder by mistake ^^.
It will take some time ^^

**Comment by guillaumecharbonnier** [comment]
I merge now because I have realized that, if the duplicates in the count table is not handled correctly by Biojupies, the best solution is to just ask in the routine workflow to compute both count tables for merge-attr and gene-names.

**Pull request merged**
